### ISSUE TITLE
Предложение по оформлению

### ISSUE THREAD

**Issue by furtivite** [punkmachine/podcast-list#1]
Я понимаю, почему сейчас сделано списком с текстовыми подпунктами-ссылками, но иногда кажется, что искать нужный сервис проще визуально, как на телефоне — мы пользуемся айдентикой и иконкой. Плюс из-за того, что это заняло бы меньше места, можно было бы сделать одним списком. 

Было:

- **Веб-стандарты**
	- Ссылки: [SoundCloud](https://soundcloud.com/web-standards), [Сайт](https://web-standards.ru), [Github](https://github.com/web-standards-ru/podcast), [YouTube](https://www.youtube.com/@webstandards_ru), [Twitter](https://twitter.com/webstandards_ru)
	
Стало:

- Веб-стандарты: [![Сайт](https://img.icons8.com/color/24/null/internet--v1.png "Сайт web-standarts.ru")](https://web-standards.ru)  [![SoundCloud](https://img.icons8.com/fluency/24/null/soundcloud.png "SoundCloud")](https://soundcloud.com/web-standards) [![GitHub](https://img.icons8.com/fluency/24/null/github.png "GitHub")](https://github.com/web-standards-ru/podcast) [![YouTube](https://img.icons8.com/fluency/24/null/youtube-play.png "YouTube")](https://www.youtube.com/@webstandards_ru) [![Twitter](https://img.icons8.com/color/24/null/twitter.png "Twitter")](https://twitter.com/webstandards_ru)

На https://icons8.com есть много иконок, их можно и сюда положить в SVG например.

**Comment by punkmachine** [comment]
Воу. Большое спасибо за отклик! Идея мне очень нравится, реализую.
